backend:
  name: github
  repo: emmanuelodhiambo237-rgb/testMixer
  branch: main
  base_url: https://github-auth.netlify.app
  auth_endpoint: /auth

media_folder: "images"
public_folder: "images"

collections:
  - name: "portfolio_data"
    label: "Portfolio Editor"
    files:
      - file: "content.json"
        label: "Edit Website Content"
        name: "content"
        fields:
          - label: "Gallery Images"
            name: "gallery"
            widget: "list"
            field: { label: "Image", name: "image", widget: "image" }
            
          - label: "Videos"
            name: "videos"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "text", widget: "text" }
              - { label: "Video File", name: "videoUrl", widget: "file" }
